import streamlit as st

st.set_page_config(
    page_title='Normal Distribution'
)

st.title('Normal Distribution')

st.sidebar.success('Select a demo above')

st.write("""
## Visualization
You can choose a visualizer to see examples of normal distribution in the sidebar
There are some visualizers for you to choose from:
- A histogram of numbers generated by NumPy's normal random number generator
- A chart of numbers in a row in Pascal Triangle
- A histogram of students' grade in the National Exam 2022
""")
